version: "3.9"

services:
  db:
    image: postgres:16.2
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - postgres-network

volumes:
  postgres_data:

networks:
  postgres-network:
