// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	GetTaskByUUID(ctx context.Context, taskUuid pgtype.UUID) (Task, error)
	GetTasksByUserUUID(ctx context.Context, userUuid pgtype.UUID) ([]Task, error)
	GetUserByUUID(ctx context.Context, userUuid pgtype.UUID) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateTaskByUUID(ctx context.Context, arg UpdateTaskByUUIDParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
